#!/bin/sh
IPADDRESS=$(awk -v i=${1} -v p=address -f /usr/share/ucarp-mvip/parseinterfaces.awk /etc/network/interfaces)
NETMASK=$(awk -v i=${1} -v p=netmask -f /usr/share/ucarp-mvip/arseinterfaces.awk /etc/network/interfaces)
#exec /sbin/ip addr add ${IPADDR}/${NETMASK} dev "$1"

# We could use ifup directly, but it complains if the address is already used
#/sbin/ifup $1

exec /sbin/ifconfig $1 ${IPADDRESS} netmask ${NETMASK} up
