#!/bin/sh
IPADDRESS=$(awk -v i=${1} -v p=address -f /usr/share/ucarp-mvip/parseinterfaces.awk /etc/network/interfaces)
NETMASK=$(awk -v i=${1} -v p=netmask -f /usr/share/ucarp-mvip/parseinterfaces.awk /etc/network/interfaces)
#exec /sbin/ip addr add ${IPADDR}/${NETMASK} dev "$1"

# We could use ifup directly, but it complains if the address is already used
#/sbin/ifup $1

# Don't start up the interface if we weren't able to parse out the required information
if [ -z "${IPADDRESS}" ] || [ -z "${NETMASK}" ]; then
  exit 1
fi
exec /sbin/ifconfig $1 ${IPADDRESS} netmask ${NETMASK} up
